version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "resourcebundle"
        versions:
          - 2.2.0
