#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License").
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""Async twin of test_aws_secrets_manager.py.

Exercises the aws_secrets_manager plugin on AsyncAwsWrapperConnection:
credential resolution via Secrets Manager ARN, secret rotation scenarios,
and error paths on invalid secrets.

Translation notes vs the sync file:
- ``AwsWrapperConnection.connect(...)`` → ``await connect_async(test_driver=..., connect_params=..., **props)``
- ``validate_connection`` (sync context manager) → ``_validate_connection_async`` (async coroutine)
- ``aurora_utility.assert_first_query_throws`` (sync) is replaced by an inline
  ``_assert_first_query_throws_async`` that awaits cursor operations.
- boto3 SDK calls (create_secret, delete_secret) stay synchronous — they may
  block briefly but that is acceptable in integration tests.
"""

from __future__ import annotations

import asyncio
import json
from typing import TYPE_CHECKING
from uuid import uuid4

import boto3
import pytest

from aws_advanced_python_wrapper.errors import (AwsWrapperError,
                                                FailoverSuccessError)
from aws_advanced_python_wrapper.hostinfo import HostRole
from aws_advanced_python_wrapper.utils.properties import Properties
from tests.integration.container.utils.async_connection_helpers import (
    assert_first_query_throws_async, cleanup_async, connect_async,
    query_host_role_async, query_instance_id_async)
from tests.integration.container.utils.conditions import (
    disable_on_features, enable_on_deployments, enable_on_features,
    enable_on_num_instances)
from tests.integration.container.utils.database_engine_deployment import \
    DatabaseEngineDeployment
from tests.integration.container.utils.rds_test_utility import RdsTestUtility
from tests.integration.container.utils.test_environment import TestEnvironment
from tests.integration.container.utils.test_environment_features import \
    TestEnvironmentFeatures

if TYPE_CHECKING:
    from aws_advanced_python_wrapper.aio.wrapper import \
        AsyncAwsWrapperConnection
    from tests.integration.container.utils.test_driver import TestDriver


# ---------------------------------------------------------------------------
# Module-level async helpers
# ---------------------------------------------------------------------------

async def _validate_connection_async(conn: AsyncAwsWrapperConnection) -> None:
    """Run a trivial query to confirm the connection is live."""
    async with conn.cursor() as cursor:
        await cursor.execute("SELECT 1")
        records = await cursor.fetchall()
        assert len(records) == 1


# ---------------------------------------------------------------------------
# Test class
# ---------------------------------------------------------------------------

@enable_on_deployments([DatabaseEngineDeployment.AURORA, DatabaseEngineDeployment.RDS_MULTI_AZ_CLUSTER])
class TestAwsSecretsManagerAsync:
    """Async test class for AWS Secrets Manager authentication."""

    @pytest.fixture(scope='class')
    def props(self):
        return Properties({
            "plugins": "aws_secrets_manager",
            "socket_timeout": 10,
            "connect_timeout": 10
        })

    @pytest.fixture(scope='class')
    def create_secret(self, conn_utils):
        """Create a secret in AWS Secrets Manager with database credentials."""
        region = TestEnvironment.get_current().get_info().get_region()
        client = boto3.client('secretsmanager', region_name=region)
        env = TestEnvironment.get_current()

        secret_name = f"TestSecret-{uuid4()}"

        engine = "postgres" if env.get_engine() == "pg" else "mysql"
        secret_value = {
            "engine": engine,
            "dbname": env.get_info().get_database_info().get_default_db_name(),
            "host": env.get_info().get_database_info().get_cluster_endpoint(),
            "username": conn_utils.user,
            "password": conn_utils.password,
            "description": "Test secret generated by integration tests."
        }

        try:
            response = client.create_secret(
                Name=secret_name,
                SecretString=json.dumps(secret_value)
            )
            secret_arn = response['ARN']
            yield secret_name, secret_arn
        finally:
            try:
                client.delete_secret(
                    SecretId=secret_name,
                    ForceDeleteWithoutRecovery=True
                )
            except Exception:
                pass

    def test_connection_async(self, test_driver: TestDriver, conn_utils, create_secret, props):
        """Test basic connection using AWS Secrets Manager."""
        secret_name, _ = create_secret
        region = TestEnvironment.get_current().get_info().get_region()

        async def inner() -> None:
            p = dict(props)
            p.update({
                "secrets_manager_secret_id": secret_name,
                "secrets_manager_region": region
            })

            conn = await connect_async(
                test_driver=test_driver,
                connect_params=conn_utils.get_connect_params(user="IncorrectUser", password="IncorrectPassword"),
                **p)
            try:
                await _validate_connection_async(conn)
            finally:
                await conn.close()
                await cleanup_async()

        asyncio.run(inner())

    def test_connect_with_arn_async(self, test_driver: TestDriver, conn_utils, create_secret, props):
        """Test connection using secret ARN."""
        _, secret_arn = create_secret

        async def inner() -> None:
            p = dict(props)
            p.update({
                "secrets_manager_secret_id": secret_arn
            })

            conn = await connect_async(
                test_driver=test_driver,
                connect_params=conn_utils.get_connect_params(user="IncorrectUser", password="IncorrectPassword"),
                **p)
            try:
                await _validate_connection_async(conn)
            finally:
                await conn.close()
                await cleanup_async()

        asyncio.run(inner())

    def test_incorrect_secret_id_async(self, test_driver: TestDriver, conn_utils, props):
        """Test connection with incorrect secret ID should fail."""
        region = TestEnvironment.get_current().get_info().get_region()

        async def inner() -> None:
            try:
                p = dict(props)
                p.update({
                    "secrets_manager_secret_id": "incorrectSecretId",
                    "secrets_manager_region": region
                })

                with pytest.raises(AwsWrapperError):
                    conn = await connect_async(
                        test_driver=test_driver,
                        connect_params=conn_utils.get_connect_params(),
                        **p)
                    await conn.close()
            finally:
                await cleanup_async()

        asyncio.run(inner())

    def test_missing_secret_id_async(self, test_driver: TestDriver, conn_utils, props):
        """Test connection with missing secret ID should fail."""
        region = TestEnvironment.get_current().get_info().get_region()

        async def inner() -> None:
            try:
                p = dict(props)
                p.update({
                    "secrets_manager_region": region
                })

                with pytest.raises(AwsWrapperError):
                    conn = await connect_async(
                        test_driver=test_driver,
                        connect_params=conn_utils.get_connect_params(user="incorrectUser", password="incorrectPassword"),
                        **p)
                    await conn.close()
            finally:
                await cleanup_async()

        asyncio.run(inner())

    def test_invalid_region_async(self, test_driver: TestDriver, conn_utils, create_secret, props):
        """Test connection with invalid region should fail."""
        secret_name, _ = create_secret

        async def inner() -> None:
            try:
                p = dict(props)
                p.update({
                    "secrets_manager_secret_id": secret_name,
                    "secrets_manager_region": "invalidRegion"
                })

                with pytest.raises(AwsWrapperError):
                    conn = await connect_async(
                        test_driver=test_driver,
                        connect_params=conn_utils.get_connect_params(user="incorrectUser", password="incorrectPassword"),
                        **p)
                    await conn.close()
            finally:
                await cleanup_async()

        asyncio.run(inner())

    def test_missing_region_async(self, test_driver: TestDriver, conn_utils, create_secret, props):
        """Test connection with missing region should fail."""
        secret_name, _ = create_secret

        async def inner() -> None:
            try:
                p = dict(props)
                p.update({
                    "secrets_manager_secret_id": secret_name
                })

                with pytest.raises(AwsWrapperError):
                    conn = await connect_async(
                        test_driver=test_driver,
                        connect_params=conn_utils.get_connect_params(user="incorrectUser", password="incorrectPassword"),
                        **p)
                    await conn.close()
            finally:
                await cleanup_async()

        asyncio.run(inner())

    def test_incorrect_region_async(self, test_driver: TestDriver, conn_utils, create_secret, props):
        """Test connection with incorrect region should fail."""
        secret_name, _ = create_secret

        async def inner() -> None:
            try:
                p = dict(props)
                p.update({
                    "secrets_manager_secret_id": secret_name,
                    "secrets_manager_region": "ca-central-1"
                })

                with pytest.raises(AwsWrapperError):
                    conn = await connect_async(
                        test_driver=test_driver,
                        connect_params=conn_utils.get_connect_params(user="incorrectUser", password="incorrectPassword"),
                        **p)
                    await conn.close()
            finally:
                await cleanup_async()

        asyncio.run(inner())

    @pytest.mark.parametrize("plugins", ["failover_v2,aws_secrets_manager"])
    @enable_on_num_instances(min_instances=2)
    @disable_on_features([TestEnvironmentFeatures.RUN_AUTOSCALING_TESTS_ONLY,
                          TestEnvironmentFeatures.BLUE_GREEN_DEPLOYMENT,
                          TestEnvironmentFeatures.PERFORMANCE])
    @enable_on_features([TestEnvironmentFeatures.FAILOVER_SUPPORTED, TestEnvironmentFeatures.IAM])
    def test_failover_with_secrets_manager_async(
            self, test_driver: TestDriver, props, conn_utils, create_secret, plugins):
        secret_name, _ = create_secret

        async def inner() -> None:
            region = TestEnvironment.get_current().get_info().get_region()
            aurora_utility = RdsTestUtility(region)
            initial_writer_id = aurora_utility.get_cluster_writer_instance_id()

            p = dict(props)
            p.update({
                "plugins": plugins,
                "secrets_manager_secret_id": secret_name,
                "secrets_manager_region": region,
                "socket_timeout": 10,
                "connect_timeout": 10,
                "monitoring-connect_timeout": 5,
                "monitoring-socket_timeout": 5,
                "topology_refresh_ms": 10,
            })

            conn = await connect_async(
                test_driver=test_driver,
                connect_params=conn_utils.get_connect_params(user="incorrectUser", password="incorrectPassword"),
                **p)
            try:
                aurora_utility.failover_cluster_and_wait_until_writer_changed()

                await assert_first_query_throws_async(conn, aurora_utility, FailoverSuccessError)

                current_connection_id = await query_instance_id_async(conn, aurora_utility)
                # Verify via the connection's data plane (pg_is_in_recovery /
                # @@innodb_read_only); the control-plane RDS API can lag the
                # data plane by tens of seconds to minutes post-failover.
                assert await query_host_role_async(conn) == HostRole.WRITER
                assert current_connection_id != initial_writer_id
            finally:
                await conn.close()
                await cleanup_async()

        asyncio.run(inner())
