name: MySQL Performance Tests

on:
  workflow_dispatch:

jobs:
  build-performance-tests:
    name: Run Performance Tests on MySQL
    runs-on: ubuntu-latest

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 8

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.4.2'

      - name: Install dependencies
        run: poetry install

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Set up Temp AWS Credentials'
        run: |
          creds=($(aws sts get-session-token \
            --duration-seconds 21600 \
            --query 'Credentials.[AccessKeyId, SecretAccessKey, SessionToken]' \
            --output text \
          | xargs));
          echo "::add-mask::${creds[0]}"
          echo "::add-mask::${creds[1]}"
          echo "::add-mask::${creds[2]}"
          echo "TEMP_AWS_ACCESS_KEY_ID=${creds[0]}" >> $GITHUB_ENV
          echo "TEMP_AWS_SECRET_ACCESS_KEY=${creds[1]}" >> $GITHUB_ENV
          echo "TEMP_AWS_SESSION_TOKEN=${creds[2]}" >> $GITHUB_ENV

      - name: 'Run MySQL Performance Tests'
        run: |
          ./gradlew --no-parallel --no-daemon test-mysql-aurora-performance --info
        env:
          AURORA_CLUSTER_DOMAIN: ${{ secrets.DB_CONN_SUFFIX }}
          AURORA_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ env.TEMP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.TEMP_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.TEMP_AWS_SESSION_TOKEN }}

      - name: 'Archive results'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-performance-report
          path: ./tests/integration/container/reports
          retention-days: 5
