name: PG Performance Tests

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-performance-tests:
    name: Run Performance Tests on PG
    runs-on: ubuntu-latest

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v4

      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 8

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.2'

      - name: Install dependencies
        run: poetry install

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: python_pg_perf_tests
          role-duration-seconds: 21600
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: 'Run PG Performance Tests'
        run: |
          ./gradlew --no-parallel --no-daemon test-pg-aurora-performance --info
        env:
          RDS_CLUSTER_DOMAIN: ${{ secrets.DB_CONN_SUFFIX }}
          AURORA_DB_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AURORA_MYSQL_DB_ENGINE_VERSION: "lts"
          AURORA_PG_ENGINE_VERSION: "lts"

      - name: 'Archive results'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-performance-report
          path: ./tests/integration/container/reports
          retention-days: 5
