name: 'Release to PyPI'

on:
  release:
    types:
      - published

jobs:
  python-wrapper-release:
    name: 'Build And Release To PyPI'
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/aws-advanced-python-wrapper/
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python 3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: 'Install poetry'
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.4.2'
      - name: 'Install dependencies'
        run: poetry install
      - name: 'Create a Package'
        run: poetry build
      - name: 'Upload to PyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
