name: Document Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  vale:
    name: Documentation Linter using Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
